### ISSUE TITLE
Logo improvement

### ISSUE THREAD

**Issue by BeastyBlacksmith** [julia-users-berlin/julia-users-berlin.github.io#27]
Now that I used our logo for the workshop, I think it could be better in terms of linking to the julia language since people not familiar with julia will not recognize that this are the "julia"-colors.
Putting the three dots on top of the "i" would be an idea that is not very inventive, but a step in the right direction.
Happy to hear your thoughts.

**Comment by rschwarz** [comment]
I'm happy with changing the logo. Maybe it can also be some `vcat` of `Julia` and `Berlin`, with the `l`s aligned, or similar.

**Comment by BeastyBlacksmith** [comment]
![berlin-users-logo](https://user-images.githubusercontent.com/18145188/67701776-e0a54a80-f9b0-11e9-8b1d-378cb0d086c9.png)
Like this?

**Comment by BeastyBlacksmith** [comment]
![berlin-users-group2](https://user-images.githubusercontent.com/18145188/67702744-958c3700-f9b2-11e9-95f6-c37e882dd322.png)
Alternative

**Comment by saschatimme** [comment]
> ![berlin-users-logo](https://user-images.githubusercontent.com/18145188/67701776-e0a54a80-f9b0-11e9-8b1d-378cb0d086c9.png)
> Like this?

Can you make a version where the Berlin is in the same font as the julia?

**Comment by rschwarz** [comment]
> Like this?

Yes, but I thought the shared `l` would be the base for the TV tower. But it does not need to be forced.

Here's an example where that theme works naturally, because of an 'O' in the upper word:
![cpaior](http://cpaior2011.zib.de/site/files/header-cpaior.png)

**Comment by BeastyBlacksmith** [comment]
> 
> Can you make a version where the Berlin is in the same font as the julia?

Thats a bit difficult, since the julia logo is handcrafted and not some common font. If someone knows of a font that looks similar, I am all ears

**Comment by rschwarz** [comment]
I think that this font exists somewhere, and that I used it to create the current logo.

**Comment by BeastyBlacksmith** [comment]
That is where I have the logo from and where I had a look at the source code

**Comment by pfitzseb** [comment]
https://github.com/JuliaLang/julia-logo-graphics/blob/master/font/TamilMN-Bold.ttf is the font.

**Comment by pfitzseb** [comment]
![julia-berlin](https://user-images.githubusercontent.com/6735977/67721736-97b4bc80-f9d7-11e9-94f8-6fcba5635bc0.png)

**Comment by pfitzseb** [comment]
![julia-berlin](https://user-images.githubusercontent.com/6735977/67722059-76080500-f9d8-11e9-9397-19a7437dc35f.png)

**Comment by BeastyBlacksmith** [comment]
@pfitzseb kannst du ein PR mit einer Version davon machen, in der die Verbindung zwischen den beiden `l`s durchgezogen ist?
