### ISSUE TITLE
Please add reference to the Data Science Co-Learning of Open Tech School

### ISSUE THREAD

**Issue by frankhuettner** [julia-users-berlin/julia-users-berlin.github.io#8]
Please add reference to the Data Science Co-Learning of OpenTechSchool, as it is appearently the only place where Julia users meet at the moment in Berlin:
https://www.meetup.com/de-DE/opentechschool-berlin/events/252848022/

Or even better: please give Sebastian Pfitzner permission to manipulate this website :)

Cheers!
Frank

**Comment by leethargo** [comment]
I'm happy to add a reference to the _Announcements_ section. Feel free to open a PR.

However, I did not see any mention of Julia on the meetup page or the linked references.

**Comment by leethargo** [comment]
Merged #9 .
